### ISSUE TITLE
Training of FlanT5 for summarization

### ISSUE THREAD

**Issue by kel-varnsen** [georgian-io/LLM-Finetuning-Hub#75]
I tried following the same framewrok for training the other llms (falcon,mistral,etc) with SFTTrainer to train the FlanT5 model as well.
But the results are bad, as if the llm doesn't learn anything.
Training it with the Seq2Seq method works. Why did you use this method for FlanT5 an SFTTrainer for all the other llms?

**Comment by benjaminye** [comment]
Hi @kel-varnsen,

Following the exact same pipeline for other LMs won't work for FlanT5 because Flan is an encoder-decoder model while the others are decoder-only models. These models are trained differently with different objectives and pre-train tasks. There are many blog posts that further explain these differences, for example [this one](https://www.practicalai.io/understanding-transformer-model-architectures/).

Good to hear that you have made it work with `Seq2SeqTrainer`.
Let me know if you have any more questions!
